### ISSUE TITLE
Use appropriate accordion `variant` instead of manually overwriting internal properties

### ISSUE THREAD

**Issue by mosguinz** [mosguinz/csc648-04-fall24-team02#51]
leaving this for now, making an accordion component messes a bunch of stuff up at the moment. i will work on this on next run, and leave in place for demo purposes. has been noted and marked for update.

_Originally posted by @WeezMatt in https://github.com/mosguinz/csc648-04-fall24-team02/pull/49#discussion_r1828602710_

**Comment by WeezMatt** [comment]
Guac 78 pull request code fixes this issue. hook for accordion has been added and updated where necessary.
